name: http_archive
description: Helps in reading '.har' (archival format for HTTP transactions) data.
# version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  meta: ^1.1.8
  equatable: 1.2.5
  json_annotation: 3.1.1

dev_dependencies:
  test: 1.15.7
  build_runner: 1.10.6
  json_serializable: 3.5.0
