name: http_archive
version: 0.1.0
description: >-
  Helps in reading/writing '.har' (archival format for HTTP transactions) data.
homepage: https://github.com/Pavel-Sulimau/http_archive

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  equatable: ^1.2.5
  json_annotation: ^3.1.1

dev_dependencies:
  test: ^1.15.7
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
