name: http_archive
version: 0.2.0
description: >-
  Helps in reading/writing '.har' (archival format for HTTP transactions) data.
homepage: https://github.com/Pavel-Sulimau/http_archive

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.3.0
  json_annotation: ^4.0.0

dev_dependencies:
  build_runner: any
  json_serializable: ^4.0.2
  test: ^1.16.0